who.are.you=prod
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.click.url=jdbc:clickhouse://127.0.0.1:8123/default
spring.datasource.click.username=default
spring.datasource.click.password=Cloud@1234
spring.datasource.click.driver-class-name=ru.yandex.clickhouse.ClickHouseDriver
spring.datasource.click.initialSize=10
spring.datasource.click.maxActive=100
spring.datasource.click.minIdle=10
spring.datasource.click.maxWait=6000

#=============== mongodb \u914D\u7F6E  =======================
spring.data.mongodb.uri=mongodb://192.168.233.10:27017/WatcherDB?replicaSet=watcherCluster
spring.data.mongodb.auto-index-creation=true
