who.are.you=dev

chEndpoint=http://192.168.233.10:8123/
chUser=default
chPassword=Cloud@1234
chDatabase=default

#=============== mongodb \u914D\u7F6E  =======================
spring.data.mongodb.uri=mongodb://192.168.233.10:27017/WatcherDB?replicaSet=watcherCluster
spring.data.mongodb.auto-index-creation=true