server.port=9999
spring.profiles.active=dev
server.servlet.context-path=/performer
spring.application.name=performer-service

mybatis.mapper-locations=classpath:mapping/*Mapper.xml
mybatis.type-aliases-package=com.virtual.cloud.om.performer.entity
mybatis.configuration.cache-enabled=true

mongodb.enable=true
