who.are.you=test

spring.data.mongodb.uri=mongodb://10.99.224.224:27017/WatcherDB
spring.data.mongodb.auto-index-creation=true
spring.kafka.bootstrap-servers=10.99.224.224:9092
# es\u96c6\u7fa4\u540d\u79f0
elasticsearch.clusterName=my-application
#es\u7528\u6237\u540d
elasticsearch.userName=elastic
#es\u5bc6\u7801
elasticsearch.password=Cloud@1234
# es host ip \u5730\u5740(\u96c6\u7fa4)\uff1a\u672c\u6b21\u4f7f\u7528\u7684\u662f\u5355\u673a\u6a21\u5f0f
elasticsearch.hosts=10.99.234.44:9200
elasticsearch.host=10.99.234.44
# es \u8bf7\u6c42\u65b9\u5f0f
elasticsearch.scheme=http
# es \u8fde\u63a5\u8d85\u65f6\u65f6\u95f4
elasticsearch.connectTimeOut=1000
# es socket \u8fde\u63a5\u8d85\u65f6\u65f6\u95f4
elasticsearch.socketTimeOut=30000
# es \u8bf7\u6c42\u8d85\u65f6\u65f6\u95f4
elasticsearch.connectionRequestTimeOut=500
# es \u6700\u5927\u8fde\u63a5\u6570
elasticsearch.maxConnectNum=100
# es \u6bcf\u4e2a\u8def\u7531\u7684\u6700\u5927\u8fde\u63a5\u6570
elasticsearch.maxConnectNumPerRoute=100
# =========================== datacenter ========================================
data.center.port=8443
# \u6279\u91cf\u6536\u96c6\u65e5\u5fd7\u6587\u4ef6\u5b58\u653e\u6839\u8def\u5f84
batch.collect.log.root.path=D:/ziptest
# ===================================================================
# uis
# ===================================================================
rest-client.uis.enable=true
uis.port=${UIS_PORT:7070}
vdi.uis.admin.username=__Internal_admin
vdi.uis.admin.password=__Internal_admin@123
# ===================================================================
# Auth
# ===================================================================
vdi.provider.operator.port=6060
vdi.provider.operator.username=__Internal_root
vdi.provider.operator.password=__Internal_root@123
# ===================================================================
# cas
# ===================================================================
rest-client.cas.enable=true
cas.http.port=${CAS_PORT:8080}
cas.https.port=${CAS_HTTPS_PORT:8443}
vdi.cas.admin.username=__Internal_admin
vdi.cas.admin.password=__Internal_admin@123
# ===================================================================
# onestor
# ===================================================================
onestor.rest.url=10.125.9.83
onestor.rest.port=8083
onestor.http.port=${ONESTOR_PORT:80}
onestor.https.port=${ONESTOR_HTTPS_PORT:443}


