who.are.you=dev

#=============== mongodb \u914D\u7F6E  =======================
spring.data.mongodb.uri=mongodb://172.53.5.202:27017/WatcherDB?replicaSet=watcherCluster
spring.data.mongodb.auto-index-creation=true


#=============== kafka \u914D\u7F6E  =======================
spring.kafka.bootstrap-servers=172.53.5.202:9092
#es
# es\u96C6\u7FA4\u540D\u79F0
elasticsearch.clusterName=wb-application
#es\u7528\u6237\u540D
elasticsearch.userName=elastic
#es\u5BC6\u7801
elasticsearch.password=Cloud@1234
# es host ip \u5730\u5740(\u96C6\u7FA4)\uFF1A\u672C\u6B21\u4F7F\u7528\u7684\u662F\u5355\u673A\u6A21\u5F0F
elasticsearch.hosts=172.53.5.201:9200
elasticsearch.host=172.53.5.201
# es \u8BF7\u6C42\u65B9\u5F0F
elasticsearch.scheme=http
# es \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
elasticsearch.connectTimeOut=1000
# es socket \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
elasticsearch.socketTimeOut=30000
# es \u8BF7\u6C42\u8D85\u65F6\u65F6\u95F4
elasticsearch.connectionRequestTimeOut=500
# es \u6700\u5927\u8FDE\u63A5\u6570
elasticsearch.maxConnectNum=100
# es \u6BCF\u4E2A\u8DEF\u7531\u7684\u6700\u5927\u8FDE\u63A5\u6570
elasticsearch.maxConnectNumPerRoute=100

# =========================== datacenter ========================================
# \u6279\u91CF\u6536\u96C6\u65E5\u5FD7\u6587\u4EF6\u5B58\u653E\u6839\u8DEF\u5F84
batch.collect.log.root.path=D:/ziptest
# ===================================================================
# uis
# ===================================================================
rest-client.uis.enable=true
uis.port=${UIS_PORT:7070}
vdi.uis.admin.username=__Internal_admin
vdi.uis.admin.password=__Internal_admin@123
# ===================================================================
# Auth
# ===================================================================
vdi.provider.operator.port=6060
vdi.provider.operator.username=__Internal_root
vdi.provider.operator.password=__Internal_root@123
# ===================================================================
# cas
# ===================================================================
rest-client.cas.enable=true
cas.http.port=${CAS_PORT:8080}
cas.https.port=${CAS_HTTPS_PORT:8443}
vdi.cas.admin.username=__Internal_admin
vdi.cas.admin.password=__Internal_admin@123
# ===================================================================
# onestor
# ===================================================================
onestor.rest.url=10.125.9.83
onestor.rest.port=8083
onestor.http.port=${ONESTOR_PORT:80}
onestor.https.port=${ONESTOR_HTTPS_PORT:443}

#clickhouse
chEndpoint=http://192.168.233.10:8123/
chUser=default
chPassword=Cloud@1234
chDatabase=default


