## Default Properties file for use by StdSchedulerFactory
## to create a Quartz Scheduler Instance, if a different
## properties file is not explicitly specified.
##
#
##\u012C\uFFFD\u03FB\uFFFD\uFFFD\uFFFD\uFFFD\u053C\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u05B6\uFFFD\uFFFD\uFFFD
#org.quartz.scheduler.instanceName = WatcherScheduler
#
##\uFFFD\uFFFD\uFFFD\u02B9\uFFFD\u00FC\uFFFD\u023A\uFFFD\uFFFDinstanceId\uFFFD\uFFFD\uFFFD\uFFFD\u03A8\u04BB\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u00F3\uFFFDAUTO
#org.quartz.scheduler.instanceId = AUTO
#org.quartz.scheduler.rmi.export= false
#org.quartz.scheduler.rmi.proxy= false
#org.quartz.scheduler.wrapJobExecutionInUserTransaction= false
#
#org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 10
#org.quartz.threadPool.threadPriority = 5
#org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread = true
#org.quartz.jobStore.misfireThreshold = 60000
#
#
##============================================================================
## Configure JobStore
##============================================================================
##
##org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
##\uFFFD\u6D22\uFFFD\uFFFD\u02BD\u02B9\uFFFD\uFFFDJobStoreTX\uFFFD\uFFFD\u04B2\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u077F\uFFFD
##org.quartz.jobStore.class=
#org.quartz.jobStore.class = com.novemberain.quartz.mongodb.MongoDBJobStore
#org.quartz.jobStore.mongoUri = mongodb://10.99.224.224:27017
#org.quartz.jobStore.dbName = WatcherDB
#org.quartz.jobStore.collectionPrefix = qrtz
##org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
##\u4F7F\u7528\u81EA\u5DF1\u7684\u914D\u7F6E\u6587\u4EF6
##org.quartz.jobStore.useProperties = true
##\u6570\u636E\u5E93\u4E2Dquartz\u8868\u7684\u8868\u540D\u524D\u7F00
##org.quartz.jobStore.tablePrefix:QRTZ_
##org.quartz.jobStore.dataSource:qzDS
##\u662F\u5426\u4F7F\u7528\u96C6\u7FA4\uFF08\u5982\u679C\u9879\u76EE\u53EA\u90E8\u7F72\u5230 \u4E00\u53F0\u670D\u52A1\u5668\uFF0C\u5C31\u4E0D\u7528\u4E86\uFF09
#org.quartz.jobStore.isClustered = true
##============================================================================
## Configure Datasources
##============================================================================
##
